#!/bin/bash

#WAZUH
#This script allows you to test your automatic reports configuration.
#It will send an e-mail from $src_mail to $dst_mail, informing about alerts generated by rule $rule_id or by group $group_id.
#Author: Sergio Peral Aguilera <sergio.peral@wazuh.com>

year=$(date +%Y)
month=$(date +%b)
day=$(date +%d)

while [ "$1" != "" ]; do
	case $1 in
		-r | --rule ) 	shift
						rule_id=$1
						;;
		-g | --group )	shift
						group_id=$1
						;;
		-s | --source )	shift
						src_mail=$1
						;;
		-d | --dest )	shift
						dst_mail=$1
						;;
		-h | --help )	echo "Usage:"
						echo "$0 [-r, --rule <rule_id> |  -g, --group <group_id> ]  -s, --source <src_email> -d, --dest <dst_email>"
						exit 1
						;;
		* )				shift
	esac
	shift
done

if [[ ! $src_mail =~ ^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$ ]]
	then
		echo "Invalid source email."
		exit 1
fi

if [[ ! $dst_mail =~ ^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$ ]]
	then
		echo "Invalid destation email."
		exit 1
fi

if [[ $rule_id =~ ^[0-9]+$ ]];
  then
    subject="Report - $day $month $year - Rule $rule_id"
		(cat /var/ossec/logs/alerts/$year/$month/ossec-alerts-$day.log | /var/ossec/bin/ossec-reportd -n "force_report.sh" -f rule $rule_id 2>&1 >/dev/null | tr -d '\015') | mailx -s "$subject" -r "$src_mail" $dst_mail
		echo "Sent 'Report - $day $month $year - Rule $rule_id' from $src_mail to $dst_mail"

elif [[ -n $group_id ]]
  then
	  subject="Report - $day $month $year - Group $group_id"
    (cat /var/ossec/logs/alerts/$year/$month/ossec-alerts-$day.log | /var/ossec/bin/ossec-reportd -n "force_report.sh" -f group $group_id 2>&1 >/dev/null | tr -d '\015') | mailx -s "$subject" -r "$src_mail" $dst_mail
		echo "Sent 'Report - $day $month $year - Group $group_id' from $src_mail to $dst_mail"

else
	echo "Usage:"
	echo "$0 [-r, --rule <rule_id> |  -g, --group <group_id> ]  -s, --source <src_email> -d, --dest <dst_email>"
fi